### PR TITLE
bloop: add JAVA_OPTS support to bloop server

### PR DESCRIPTION
**Pull request by svalaskevicius**
###### Motivation for this change

added JAVA_OPTS to allow settings java parameters to the server (such as Xss, Xmx etc). thought I could add it to your PR. No worries if you prefer to keep it separate - I can send a new PR once yours is merged :)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by svalaskevicius** [comment]
hmm, thought I'll escape it better. 1 moment - please don't merge yet

**Comment by svalaskevicius** [comment]
actually, seems like there is no other good way to escape it - given as it's read from env var... let me know if you can think of any, but it seems I'll have to leave it as is at least for now

**Comment by Tomahna** [comment]
Depends on what you aim to achieve. If it is ok to have a somewhat static config, you could add a parameter to the derivation and use it.

For example, for metals I do have javaOpts defined at the derivation level (https://github.com/NixOS/nixpkgs/pull/60336) which seem to work properly.

You could pull the extraJavaOpts and put them as derivation arguments so that they can be overriden by the nix configuration.

**Comment by svalaskevicius** [comment]
Hmm in my pr it leaves it configurable at runtime - I have a custom systemd unit file that starts it as a service - but just for the user

**Comment by svalaskevicius** [comment]
If applied at derivation level - I think it should be customisable by users - eg we cannot know what ram allocation they want to /can give to the java process.

Is it possible to override this config when installing via nix-env?

**Comment by Tomahna** [comment]
> Hmm in my pr it leaves it configurable at runtime - I have a custom systemd unit file that starts it as a service - but just for the user

Note that services.bloop.install = true will install a systemd service at user level, not root level.

> If applied at derivation level - I think it should be customisable by users - eg we cannot know what ram allocation they want to /can give to the java process.

I completely agree, but you can have configurable derivation parameters. (you can look for example at the polybar package where you can configure a few options)

> Is it possible to override this config when installing via nix-env?

Probably but it would be a bit annoying to do.

**Comment by Tomahna** [comment]
I need a bit of time to think about it. My main problem with this way of doing thing is that we are getting further of the way bloop documents (https://scalacenter.github.io/bloop/docs/server-reference). Eg: -J-Xmx=256M.

So I'm wondering if we cannot go closer to the way bloop does thing on other systems and actually solve several problems at once.

**Comment by svalaskevicius** [comment]
That would be good but it doesn't look as easy.. Although maybe I'm wrong :) just had some problems starting the server via the bloop script - found it easier to just invoke the wrapped server script

**Comment by Tomahna** [comment]
I'm looking to it on the bloop-jvmopts branch. It looks possible, and I should even be able to fix a few other problems like making ```bloop server``` work properly.

**Comment by Tomahna** [comment]
Yup it does seem to work properly. I've added it to the current PR. It fixes many small problems

**Comment by svalaskevicius** [comment]
Thanks! I'll try it (hopefully soon) :)

Closing this pr in the meanwhile

**Pull request closed without merging**
